version: '3'
services:
  # database
  mysql:
    image: mysql:5.7
    volumes:
      - ./db/data:/var/lib/mysql
    command:
      - "--default-authentication-plugin=mysql_native_password"
    environment:
      MYSQL_ROOT_PASSWORD: "toor"
      MYSQL_DATABASE: "php-roguelike"
      MYSQL_USER: 'php-roguelike'
      MYSQL_PASSWORD: 'password123'
    ports:
      - "3306:3306"

  # php app
  app:
    build: .
    tty: true
    depends_on:
      - mysql
    links:
      - mysql
    command: tail -f /app/var/log/dev.log

volumes:
  mysql: